version: '3.7'
services:

    wordpress:
      build:  wordpress/
      image:  pleveque/wordpress:stable
      container_name: wordpress
      volumes:
        - "/home/pleveque/data/www:/var/www"
      networks:
        - backend
        - frontend
      restart: always
      environment:
        MYSQL_HOST:       ${MYSQL_HOST}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
        DOMAIN_NAME:      ${DOMAIN_NAME}
        WP_TITLE:         ${WP_TITLE}
        WP_ADMIN_USR:     ${WP_ADMIN_USR}
        WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
        WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
        WP_USR:           ${WP_USR}
        WP_PWD:           ${WP_PWD}
        WP_EMAIL:         ${WP_EMAIL}

    nginx:
      build:  nginx/
      image:  pleveque/nginx:stable
      container_name: nginx
      ports:
        - 443:443
      networks:
        - frontend
      restart: always
      volumes:
        - "/home/pleveque/data/www:/var/www"
    
    mariadb:
      build: mariadb/
      image:  pleveque/mariadb:stable
      container_name: mariadb
      networks:
        - backend
      restart: always
      volumes:
        - "/home/pleveque/data/database:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

networks:
    backend:
    frontend:
